name: AMI Build

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create webservice Folder
        run: rsync -arv --exclude='package-lock.json/' --exclude='.gitignore' . ./webservice
      - name: Switch to webservice Folder
        run: |
          zip -r webservice.zip webservice
      - uses: actions/upload-artifact@v1
        with:
          name: webservice.zip
          path: ${{ github.workspace }}/webservice.zip
        
  buildartifact:
    runs-on: ubuntu-latest
    needs: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with: 
         name: webservice.zip
      - name: Display structure of downloaded files
        run: ls -d $PWD/*

      # Runs a single command using the runners shell
      - name: Packer Build
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: "packer/ami.json"
          workingDir: '.'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
          AMI_USERS: ${{ secrets.AMI_USERS }}
          AWS_VPC_ID: ${{ secrets.AWS_VPC_ID }}